### ISSUE TITLE
Add support for REST

### ISSUE THREAD

**Issue by raulgomis** [j-easy/easy-batch#286]
It would be nice to add support for REST readers and REST writers (webhooks). It would allow to integrate to different services that support webhook integration (slack, jira, etc.)

**Comment by benas** [comment]
Yes, we should think about the record type. I think StringRecord is ok but it should be consistent (some APIs return json, other xml, etc).

I'm using something similar but without a specific RestReader:

https://gist.github.com/benas/36f6b5f0fe3ca5364aa813b20ddfa74c

It uses easy batch to generate the release notes of easy batch 😉

**Comment by raulgomis** [comment]
haha good example! That could be an option with the current design but it would be easier with a RestReader that handles the retries, timeouts... for you, don't you think so? ;) I am very lazy!

**Comment by benas** [comment]
Sure!

There are still many things to do on easy batch, if only I have a chance to work on it fulltime..

**Comment by prudhvikonda** [comment]
Hey @benas ,
I'm new to using projects and communication on github, so sorry if I'm commenting at the wrong place. Firstly, I really liked the idea and the feature set of easy-batch so wanted to extend my thanks to you and all the contributors for the awesome code and documentation 👍 

The question I wanted to post is related to this issue so adding it here. As mentioned, I wish there were REST readers and writers. I have gone through your implementation for an alternative way to read but I'm looking for an alternative way to POST to a REST API. I just wanted to know your thoughts on that. 

My requirement is to read a million records from a csv file and POST 50 records to a REST API. So, is there a way that you can suggest me to implement this with the current easy-batch functionality. Can I leverage any of the post job or post batch listeners for doing this. The idea that I have currently is to create the payload using the writer and invoke the REST API in the post listener.

Please let me know your thoughts about it. Thank you so much!

- Prudhvi Konda

**Comment by benas** [comment]
After some research on this, it turns out that REST APIs differs significantly in terms of how they manage pagination, authentication, content type, etc. Hence, trying to come up with a generic REST reader/writer could be problematic.

I believe one can leverage the existing Json/XML/Yaml readers to consume/produce data from/to REST APIs by giving the endpoint's input/output stream to a suitable reader/writer. I have added a complete tutorial on that matter: https://github.com/j-easy/easy-batch/tree/master/easy-batch-tutorials/src/main/java/org/jeasy/batch/tutorials/intermediate/rest

This tutorial shows how to consume data from Github's REST API to generate a release note for an Easy Batch milestone. As the example shows, giving the input stream of a URL connection to a `JsonRecordReader` does the trick (the same is possible with a writer). So I'm closing this issue.

@prudhvikonda 

>  Firstly, I really liked the idea and the feature set of easy-batch so wanted to extend my thanks to you and all the contributors for the awesome code and documentation 👍

Thank you! I'm glad you like it.

> My requirement is to read a million records from a csv file and POST 50 records to a REST API. So, is there a way that you can suggest me to implement this with the current easy-batch functionality. Can I leverage any of the post job or post batch listeners for doing this. The idea that I have currently is to create the payload using the writer and invoke the REST API in the post listener.

I would do that in a record writer and not a listener. POST/PUT requests are some kind of write operations, so it's fine to implement them in a record writer. In your case, I would use the `FlatFileRecordReader` and set the batch size to 50, then with a custom writer you can send a POST request with the 50 records as payload.
