### ISSUE TITLE
Add support for ElasticSearch

### ISSUE THREAD

**Issue by raulgomis** [j-easy/easy-batch#288]

**Comment by benas** [comment]
Even tough it's great to have extensions for many third party tools (I'm thinking of elasticsearch, redis, cassandra and others), these extensions have a huge maintaince effort! These tools are moving fast, updated frequently and we have to catch up.

For instance, as of today, support for mongo db in easy batch is not up to date. Mongo APIs have changed, the driver version has been updated by mongo, etc But I did'nt have time to follow.

Same for other extensions.

I even wanted to add [support for neo4j](https://github.com/j-easy/easy-batch/issues/84) but abondonned it because of lack of time.

Anyway, do you want to join forces and become a member of the @j-easy/easy-batch-team ? You'll have full access to the repo and lead the development and maintaince of any extension of your choice (kafka, rest, elastic..). Of course, you can contribute to the core module if you want. What do you think?

**Comment by benas** [comment]
To give you a bit of context, I created jeasy umbrella project a few weeks ago and I'm busy releasing two more projects (easy-jobs and easy-flows). Those are tools I've successfully used for many years and I decided to open source everything. I've created a team for each project and I'm planning to invite a lot of enthusiastic, passionate oss contributors to help out. You are one of them.

I do strongly believe having a community of users and contributors is the most important factor of the success of any oss project. So once I finish releasing all projects, I'll start working on this aspect.

**Comment by raulgomis** [comment]
Hi @benas!

Thanks for the explanation! Yes, I think I would be able to help next month, as currently I am moving overseas. Regarding the maintenance, you are right, they require great effort. Probably, we should focus on creating the extensions for the most trendy technologies: Kafka and Cassandra first (apart from updating the MongoDB one). And see if we get more community that helps us with other connectors / extensions. There are much more use cases or ideas we could do to automate business workflows with easy-batch: Emails, Twitter, Twilio, Slack, Trello, Dropbox, Google drive, AWS, etc. 

Btw, congrats for the project, it has a great design & implementation.

**Comment by benas** [comment]
> Btw, congrats for the project, it has a great design & implementation.

Thank you! I'm glad you like it.

As discussed previously in regards to the maintenance burden, I'm closing this issue for now. Contributions are welcome to add support for third party libraries and tools.
