### ISSUE TITLE
Add support for Java 8 date/time classes

### ISSUE THREAD

**Issue by Jcamilorada** [j-easy/easy-batch#311]
Hello Guys

is being sometime since java 8 and I am wondering if there is any plan to support java 8 date types in [Header](https://github.com/j-easy/easy-batch/blob/master/easybatch-core/src/main/java/org/easybatch/core/record/Header.java).  I can work in pr if this is in your plans.

**Comment by benas** [comment]
yes, Java 8 support is planned for next major version v6.

There is some work I want to do before migrating to Java 8 APIs (streams, date/time, etc), mainly changing the base package to `org.jeasy` and restructuring some modules. When done, I will let you know and you are welcome to contribute!

**Comment by benas** [comment]
Hi @Jcamilorada 

The work I planned to do for v6 is now done. You are welcome to contribute a PR if you want.

In the `Header` class, the constructor and the `getCreationTime` getter were deprecated in v5.3 and can be safely removed. We can replace them to use `java.time.LocalDateTime` instead of `java.util.Date`.

Are you willing to contribute a PR? Otherwise please let me know asap and I will do it.

Regards,
Mahmoud

**Comment by benas** [comment]
Resolved with 6ed067ad935c902cdd189d927e1d4970524b7670.
