### ISSUE TITLE
Add FileRecordSourceNamedWriter

### ISSUE THREAD

**Issue by bgfeldm** [j-easy/easy-batch#331]
Create a File Record Writer which uses **Header source for the filename**
and accept a parameter for output suffix.

new FileRecordSourceNamedWriter("out")

Reading File1.csv --> Write File1.out
Reading File2.csv --> Write File2.out

Another option would be to set a **record limit per file**

Reading File1.csv --> Write [ File1-part1.out , File1-part2.out ]

**Comment by benas** [comment]
Hi @bgfeldm,

Thank you for opening this issue. I believe we don't need a new concept `FileRecordSourceNamedWriter` for this use case since we have control over file names when creating the record reader/writer. In your example, you can create a `FlatFileRecordReader("File1.csv")` and a corresponding `FileRecordWriter("File1.out")`.

I'm closing this issue for now, but feel free to add a comment if needed.
