### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by zivziv77** [j-easy/easy-batch#335]
Hi,
I am willing to contribute rabbitMQ reader and writer.
I have a question: How can it be implemented if the reader is push?
I mean the reader of RabbitMQ is actually a listener which gets the messages and not pulling them, Is that possible at all?

**Comment by benas** [comment]
You are welcome to contribute, thank you for proposing help!

The reader should not be a listener, it should poll the queue until an item is available, otherwise after a configurable timeout, it should return null which would end the job.

I'm closing this issue. If you want to contribute, please open a PR.
