### ISSUE TITLE
Allow to set/unset auto-commit mode for connections in JdbcRecordReader

### ISSUE THREAD

**Issue by cristhiank** [j-easy/easy-batch#343]
I'm having an issue with some JDBC driver that follows the JDBC 3.0 spec that says:
```
/* 
* According to the JDBC 3.0 specification (p.62) the result set
* is closed in the autocommit mode if one of the following occurs: 
* 
* - all of the rows have been retrieved
* - the associated Statement object is re-executed
* - another Statement object is executed on the same connection
*/
```
So I am getting a nasty exception because the ResultSet is closed when reader ends reading all rows, but not all batches have been executed.

The JdbcRecordReader should allow to set the connection auto-commit property to avoid this conflict.

**Comment by benas** [comment]
This is not related to the auto-commit property of the connection, it is because `JdbcRecord`s hold a reference to the `ResultSet` (this is due to a limitation in the JDBC API which does not provide an abstraction for a single row).

What you need to do in your case is to map JDBC records to domain objects and dispatch these objects to asynchronous workers. This is actually documented here: https://github.com/j-easy/easy-batch/wiki/writers#performance-notes

I'm closing this issue for now, but feel free to add a comment here if you need further support.
