### ISSUE TITLE
CDI and property injection support

### ISSUE THREAD

**Issue by salvadormarcos** [j-easy/easy-batch#344]
Would it be possible to add support for the CDI and property injection (@BatchProperty) inside the beans (Reader, Writer, etc) just like in JSR 352?

**Comment by benas** [comment]
No that's is not possible because Easy Batch does not create your reader, writer, etc. Hence it does not do any dependency or property injection.

That said, if you use Easy Batch in a DI container, you can declare your reader/writer as managed objects and benefit from the DI features (an [example](https://github.com/j-easy/easy-batch/blob/master/easybatch-tutorials/src/main/resources/org/easybatch/tutorials/advanced/spring/application-context.xml) can be found in the [spring tutorial](https://github.com/j-easy/easy-batch/tree/master/easybatch-tutorials/src/main/java/org/easybatch/tutorials/advanced/spring)).
