### ISSUE TITLE
Resource leak in FileRecordReader

### ISSUE THREAD

**Issue by EDReolon** [j-easy/easy-batch#394]
Hello,

A colleague and me saw than stream opened on this ligne was never closed:
https://github.com/j-easy/easy-batch/blob/f93826a463604ec6f1874fecab0c79096b9de3dd/easy-batch-core/src/main/java/org/jeasy/batch/core/reader/FileRecordReader.java#L76

So, if you work in a sub structure file like:
[root]
-[sub directory]
--> files to process

And after finishing the job, if you try to delete the root file, the sub directory will be not able to remove before ending the java process and you will receive a IOException.

Reference:
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#list-java.nio.file.Path-
If an IOException is thrown when accessing the directory after this method has returned, it is wrapped in an UncheckedIOException which will be thrown from the method that caused the access to take place. 

So, I rewriting the same class putting Stream<Path> pathStream in class field and add in the close method of reader these lines:
	public void close() {
		pathStream.close();
	}

I hope this issue will help you, because I like the simplicity of your project/product.

Best Regards,
Dario

**Comment by benas** [comment]
Hi @EDReolon ,

Thank you for raising this issue. Indeed, this is a bug in Easy Batch. The stream should be closed after use. I pushed a fix in 7.0.2-SNAPSHOT. Can you give it try? If this works for you, I will release it in 7.0.2 asap.

**Comment by benas** [comment]
@EDReolon Have you got a chance to test the fix in [7.0.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots)?

**Comment by EDReolon** [comment]
Hello @benas ,

I found something else about the stream:
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#list-java.nio.file.Path-
The stream is weakly consistent. It is thread safe but does not freeze the directory while iterating, so it may (or may not) reflect updates to the directory that occur after returning from this method.  

Is it an expected behavior ?
This behavior did not happen in v 5.2.0 as no stream was used.

If not, the stream can be closed in the open method. 

Best regards,
Dario

**Comment by benas** [comment]
> The stream [...] does not freeze the directory while iterating, so it may (or may not) reflect updates to the directory that occur after returning from this method. 

This is how Java streams work, and not related to Easy Batch. Batch processing is about fixed, immutable data set. If your input folder is a moving target, batch processing tools are not the right tool for you, streaming solutions are more appropriate. You should be designing your jobs to work against a fixed folder content.

**Comment by EDReolon** [comment]
Yes, the issue is fixed.

But (another case), imagine you have a long running batch that process files from a directory.

When the batch is running, 2 more files land in that directory. As the stream is weakly consistent, these 2 new files may or may not be processed .  This behavior is different from v5.2.0 where the files to be processed were the files that existed when the batch started.

**Comment by benas** [comment]
> Yes, the issue is fixed.

ok thanks. 7.0.2 has been released with the fix included.

> But (another case), imagine you have a long running batch that process files from a directory. When the batch is running, 2 more files land in that directory. As the stream is weakly consistent, these 2 new files may or may not be processed . 

As mentioned in my previous comment, a folder with a non-fixed content is not a finite dataset, which is typically out of scope of batch applications. I see this no different from a queue that can receive messages while the job is running. You need to write a separate code that monitors the folder (like a [WatchService](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/WatchService.html) for instance) and launches a job for each incoming file. It is not the `FileRecordReader`'s responsibility to continuously wait for files to arrive, otherwise your job might never end.

> This behavior is different from v5.2.0 where the files to be processed were the files that existed when the batch started.

I don't see how this is different from v5.2. In v5.2, the reader was using a list of files, which is fixed once created at job startup. So even if new files arrive in the folder while the job is running, they won't be added to the initial list.

v7 uses a stream instead of a list, which does not freeze the folder (as you mentioned in its javadoc) and any file that arrives in the folder after the stream is initialized won't be processed. So the behaviour is the same.
